services:

  news-feed-api:
    build:
      context: .
      dockerfile: ./dockerfile
#      target: development    # For development
#    command: yarn start:dev  # For development
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.6
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./mongodb:/data/db