services:

  news-feed-api:
    build:
      context: .
      dockerfile: ./dockerfile
      target: development
    command: yarn start:dev
    ports:
      - 8000:8000
    volumes:
      - .:/usr/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.6
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./mongodb:/data/db